/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package belajar.gradle

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

// klo mau jalanin ini bisa ke terminal trus make kata kunci gradle test
class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
        assertEquals(classUnderTest.greeting, "Hello World!")
    }
}
