/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package belajar.gradle

import com.google.gson.Gson

// klo mau jalanin ini bisa ketik gradle classes di terminal
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    val gson = Gson()
    println(gson)
}
